### ISSUE TITLE
GSscraper

### ISSUE THREAD

**Issue by lottiegasp** [langcog/metalab#79]
Try the R package GSscraper for conducting a Google Scholar search, and if suitable, add to the tutorial materials

https://youtu.be/2o4PBUBbWAE?t=53

**Comment by lottiegasp** [comment]
Possibly to use in combo with revtools https://revtools.net/assets/docs/Westgate_revtools_bioRxiv_v2.pdf or metagear to assist w allocating efforts between reviewers and aggregating results

**Comment by lottiegasp** [comment]
Also revtools or ASySD https://camarades.shinyapps.io/RDedup/ to identify duplicates

**Comment by christinabergmann** [comment]
I used this tool: https://harzing.com/resources/publish-or-perish
It has the advantage over GSpraper that it does return tables, otherwise it seems similar because the limitations come from google, not the tools. 

To split screening word, I've seen people talk about rayyan but it didn't seem to add anything, for me the table system we use on drive seems still the one with the lowest hurdle.

**Comment by lottiegasp** [comment]
Thanks @christinabergmann  I also used Publish or Perish and thought it worked well so happy to leave as is if you don't think GScraper adds any advantages :)
